[tool.poetry]
name = "todoist-analytics"
version = "0.0.0"
description = ""
authors = ["Bruno Rodrigues <b.rosilva1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
todoist-python = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^3.4.2"
streamlit = "^0.74.0"
myst-parser = "^0.13.1"
pydata-sphinx-theme = "^0.4.1"
ghp-import = "^1.0.0"
pandas = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
